theme: jekyll-theme-cayman
title: Algoim
description: Algorithms for implicitly defined geometry, level set methods, and Voronoi implicit interface methods
google_analytics: UA-127740713-1
show_downloads: true
github:
    is_project_page: true
    repository_url: https://github.com/algoim/algoim
    zip_url: https://github.com/algoim/algoim/zipball/master
    tar_url: https://github.com/algoim/algoim/tarball/master
